---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gostatsd-cfg
  namespace: default
data:
  config.toml: |
    backends=['newrelic']
    default-tags=[]
    internal-tags=['in_cluster:true']
    statser-type='internal'
    flush-interval='10s'
    bad-lines-per-minute=1000
    metrics-addr=':8125'
    filters='no-hostname'
    ignore-host=false

    [filter.no-hostname]
    # Drop the hostname from metrics because it can be very noisy with pod churn on Kubernetes
    drop-host=false

    [k8s]
    watch-cluster=true

    [newrelic]
    flush-type = "metrics"
    transport = "default"
    # Edit
    address = "https://insights-collector.newrelic.com/v1/accounts/YOUR_NEW_RELIC_ACCOUNT_ID/events"
    # EU Accounts
    #address = "https://insights-collector.eu01.nr-data.net/v1/accounts/YOUR_NEW_RELIC_ACCOUNT_ID/events"
    # FedRAMP
    #address = "https://gov-insights-collector.newrelic.com/v1/accounts/YOUR_NEW_RELIC_ACCOUNT_ID/events"
    # Edit
    address-metrics = "https://metric-api.newrelic.com/metric/v1"
    # EU Accounts
    #address-metrics = "https://metric-api.eu.newrelic.com/metric/v1"
    # FedRAMP
    #address-metrics = "https://gov-metric-api.newrelic.com/metric/v1"
    # Edit
    api-key = "YOUR_NEW_RELIC_LICENSE_KEY"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gostatsd
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gostatsd
  namespace: default
  labels:
    app: gostatsd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gostatsd
  template:
    metadata:
      labels:
        app: gostatsd
    spec:
      serviceAccountName: gostatsd
      containers:
      - name: gostatsd
        imagePullPolicy: IfNotPresent
        image: atlassianlabs/gostatsd:latest
        ports:
        - containerPort: 8125
        command: ['/bin/gostatsd', '--cloud-provider', 'k8s', '--verbose', '--config-path', '/etc/gostatsd-cfg/config.toml']
        volumeMounts:
        - name: config
          mountPath: /etc/gostatsd-cfg
      volumes:
      - name: config
        configMap:
          name: gostatsd-cfg
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gostatsd
  name: gostatsd
  namespace: default
spec:
  ports:
    - name: udp-metrics
      port: 8125
      protocol: UDP
      targetPort: 8125
  selector:
    app: gostatsd
  type: ClusterIP
